#!/bin/bash

#define
PRIME=1
NO_PRIME=0

num1=0
num2=0

PrimeList={}

#init
function init()
{
	local size=${num2}+1

	for ((i=0;i<=$size;$((i=i+1))))do
		PrimeList[${i}]=$PRIME
	done	
		PrimeList[0]=$NO_PRIME
		PrimeList[1]=$NO_PRIME
}


#swap
function swap()
{
	local temp=0

	echo "swap start"

	temp=num1
	num1=num2
	num2=temp

	echo "swap end"

	echo "${num1} ${num2}"
	
	return 
}

#check prime

function checkPrime()
{
	local index

	for ((i=2;i<=num2;i++));do
		for ((j=2;i*j<=num2;j++));do
			echo "${i}*${j} = $(( i * j))"
		
			index=$((i*j))
			
			if [PrimeList[${index}] -eq 0];then
				continue
			fi
			echo "index = ${index}"
		
			PrimeList[${index}]=$NO_PRIME
		done

	done

	return
}
#input
function input()
{
	echo -e "두 숫자를 입력하세요: "
	read num1 num2

	echo "num1 num2"

	Prime_List=('seq 1 ${num2}')
	echo ${Prime_List[@]} 
	return
}

#print
for ((i=2;i<=num2;i++));do
	if [PrimeList[${i}] -eq 1]; then
		echo "i = ${i}"
	fi
done

#main

input
echo "${num1} ${num2}"
init
echo ${PrimeList[@]}
checkPrime
